name: Auto Increment Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Get changed files
        id: changes
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > files_changed.txt
          if grep -q "^version$" files_changed.txt; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Read current version
        if: steps.changes.outputs.skip == 'false'
        id: read_version
        run: |
          version=$(cat version)
          echo "current=$version" >> $GITHUB_OUTPUT

      - name: Increment version
        if: steps.changes.outputs.skip == 'false'
        id: bump
        run: |
          ver=${{ steps.read_version.outputs.current }}
          IFS='.' read -r major minor build <<< "$ver"
          build=$(printf "%03d" $((10#$build + 1))) # force decimal, keep leading zeros
          new_ver="$major.$minor.$build"
          echo "$new_ver" > version
          echo "new=$new_ver" >> $GITHUB_OUTPUT

      - name: Commit new version
        if: steps.changes.outputs.skip == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version
          git commit -m "ci: bump version to ${{ steps.bump.outputs.new }}"
          git push
